services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file: 
      - ./backend/.env
    restart: always
    container_name: backend-app
    networks:
      - app-network  # Add this line

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://backend:5000  # Ensure this matches .env
    restart: always
    container_name: frontend-app
    networks:
      - app-network  # Add this line

networks:
  app-network:  # Define a custom network
    driver: bridge
