version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:4000"
    env_file: 
      - ./backend/.env
    restart: always
    container_name: backend-app

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://backend:4000
    restart: always
    container_name: frontend-app

networks:
  app-network:  # Define a custom network
    driver: bridge
